'use client'

import { useEffect, useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { useApp } from '../../../../App'

type Address = { id: string; fullName: string; phone: string; addressLine1: string; addressLine2: string; landmark: string; city: string; state: string; pincode: string; country: string; isDefault: boolean }
const empty: Omit<Address, 'id'> = { fullName: '', phone: '', addressLine1: '', addressLine2: '', landmark: '', city: '', state: '', pincode: '', country: 'India', isDefault: false }

export default function AddressesPage() {
  const { user, authLoading } = useApp(); const router = useRouter()
  const [addresses, setAddresses] = useState<Address[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function load() { const response = await fetch('/api/addresses', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAddresses(data.addresses || []) }
  useEffect(() => { if (!authLoading && !user) router.replace('/login?next=/account/addresses'); if (user) void load().catch(e => setError(e.message)) }, [user, authLoading, router])
  if (authLoading || !user) return <div className="p-16 text-center">Loading…</div>
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch('/api/addresses', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, ...(editing ? { id: editing } : {}) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setForm(empty); setEditing(''); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save address.') } finally { setBusy(false) } }
  async function remove(id: string) { setError(''); const response = await fetch(`/api/addresses?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) setError(data.error); else await load() }
  return <div className="mx-auto max-w-5xl px-4 py-12"><h1 className="font-display text-3xl text-brand">Address book</h1>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={save} className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">{editing?'Edit address':'Add a delivery address'}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['fullName','Full name'],['phone','Phone'],['addressLine1','Address line 1'],['addressLine2','Address line 2'],['landmark','Landmark'],['city','City'],['state','State'],['pincode','Pincode'],['country','Country']] as const).map(([key,label])=><label key={key} className="text-sm">{label}<input required={['fullName','phone','addressLine1','city','state','pincode'].includes(key)} value={form[key]} maxLength={200} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 h-10 w-full rounded-lg border px-3"/></label>)}</div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/>Set as default</label><div className="mt-4 flex gap-3"><button disabled={busy} className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">{busy?'Saving…':'Save address'}</button>{editing&&<button type="button" onClick={()=>{setEditing('');setForm(empty)}} className="rounded-lg border px-4 py-2 text-sm">Cancel</button>}</div></form><div className="mt-6 grid gap-3 md:grid-cols-2">{addresses.map(address=><article key={address.id} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{address.fullName} {address.isDefault&&<span className="ml-2 text-xs text-accent">Default</span>}</p><p className="mt-2 text-sm text-slate-600">{address.phone}<br/>{address.addressLine1} {address.addressLine2}<br/>{address.landmark&&`${address.landmark}, `}{address.city}, {address.state} {address.pincode}, {address.country}</p></div><div className="flex shrink-0 flex-col gap-2"><button onClick={()=>{setEditing(address.id);setForm({ fullName:address.fullName, phone:address.phone, addressLine1:address.addressLine1, addressLine2:address.addressLine2, landmark:address.landmark, city:address.city, state:address.state, pincode:address.pincode, country:address.country, isDefault:address.isDefault })}} className="text-sm font-medium text-accent">Edit</button><button onClick={()=>void remove(address.id)} className="text-sm text-red-600">Delete</button></div></div></article>)}</div></div>
}
